/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.VentanaMenuApartamentoControlador;
import Controlador.VentanaMenuEdificioControlador;
import static Controlador.VentanaMenuEdificioControlador.devuelvedireccionSQL;
import static Interfaz.VentanaMenuPropietario.modelo;
import static Interfaz.VentanaMenuRoles.modelo;
import Modelo.Util;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.and;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus Trejo
 */
public class VentanaMenuEdificio extends javax.swing.JFrame {

    public static String ClaveEstado = null;
    public static String ClaveMunicipio = null;
    public static String ClaveParroquia= null;
    public static int Opcion = 0;
    public static DefaultTableModel modelo = new DefaultTableModel(); 
    public static int cont = 0;
    public static boolean AreaValida = false;
    public static ArrayList<String> AreasComunes = new ArrayList();
    public static boolean ActivaCombo=false;
    public static ArrayList<String> PermisosActuales = new ArrayList();

    
    public VentanaMenuEdificio() throws SQLException {
        initComponents();
        cargarInterfaz();
    
        Tabla.addKeyListener( new KeyAdapter() {} );
      
        PanelAPT.setVisible(false);
        //btnAyuda.setVisible(false);
        ComboEstados.setVisible(false);
        ComboMunicipio.setVisible(false);
        ComboParroquia.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        AC1.setVisible(false);
        AC2.setVisible(false);
        AC3.setVisible(false);
        AC4.setVisible(false);
        AC5.setVisible(false);
        AC6.setVisible(false);
        AC7.setVisible(false);
        AC8.setVisible(false);
        AC9.setVisible(false);
         AC10.setVisible(false);
         Tabla.setVisible(false);
       ComboEstados.setVisible(false);
       ComboMunicipio.setVisible(false);
       ComboParroquia.setVisible(false);
       TXTNombre.setVisible(false);
       TXTRif.setVisible(false);
      
       try{
       VentanaMenuEdificioControlador.RellenaTablaSQL();
       }catch (Exception e){
           JOptionPane.showMessageDialog(rootPane,"REVENTO EN ->"+e);
       }
       VentanaMenuEdificioControlador.LlenarEstado();
            for (String x: VentanaMenuEdificioControlador.Estados){
                ComboEstados.addItem(x);
            }
        JOptionPane.showMessageDialog(rootPane, "PARA REALIZAR ALGUNA OPERACION DEBE ESPECIFICAR QUE ACCION DESEA REALIZAR.");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComboOpcion = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboEstados = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        ComboMunicipio = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        AC1 = new javax.swing.JCheckBox();
        AC2 = new javax.swing.JCheckBox();
        AC3 = new javax.swing.JCheckBox();
        AC4 = new javax.swing.JCheckBox();
        AC5 = new javax.swing.JCheckBox();
        AC6 = new javax.swing.JCheckBox();
        AC7 = new javax.swing.JCheckBox();
        AC8 = new javax.swing.JCheckBox();
        AC9 = new javax.swing.JCheckBox();
        AC10 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnFinalizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboParroquia = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        TXTRif = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TXTNombre = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        PanelAPT = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMedidas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();

        jCheckBox9.setText("jCheckBox1");

        jLabel10.setText("Apartamentos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Menu Edificio");

        ComboOpcion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ComboOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Crear Edificio\t", "Mostrar Edificio", "Editar Edificio", "Eliminar Edificio" }));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Selecione la operacion que desea realizar");

        Tabla.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rif", "Nombre", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        Tabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Lista de Edificios Existentes en el sistema");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Datos Generales del Edificio");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Especifique la direccion del Edificio");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Estado");

        ComboEstados.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ComboEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboEstadosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ComboEstadosMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Municipio");

        ComboMunicipio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ComboMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ComboMunicipioMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ComboMunicipioMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Areas Comunes Disponibles");

        AC1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC1.setText("Piscina");

        AC2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC2.setText("Canchas Deportivas");

        AC3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC3.setText("Sauna");

        AC4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC4.setText("Gimnasio");

        AC5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC5.setText("Recepcion");

        AC6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC6.setText("Estacionamiento");
        AC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC6ActionPerformed(evt);
            }
        });

        AC7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC7.setText("Ascensor");

        AC8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC8.setText("Areas Verdes");

        AC9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC9.setText("Parque Infantil");

        AC10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AC10.setText("Sala De Juegos");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnFinalizar.setText("Finalizar");
        BtnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalizarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel8.setText("Parroquia");

        ComboParroquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboParroquiaActionPerformed(evt);
            }
        });

        jLabel12.setText("Rif:");

        jLabel13.setText("Nombre:");

        TXTNombre.setText("jTextField3");

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        PanelAPT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario para Apartamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu Medium", 0, 18))); // NOI18N

        jLabel11.setText("Cantidad de apartamentos en el edificio");

        jLabel14.setText("Medidas Generales de los Apartamentos");

        jLabel16.setText("Indique el precio que tendran los apartamentos");

        txtprecio.setText("1000000");

        javax.swing.GroupLayout PanelAPTLayout = new javax.swing.GroupLayout(PanelAPT);
        PanelAPT.setLayout(PanelAPTLayout);
        PanelAPTLayout.setHorizontalGroup(
            PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAPTLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAPTLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtprecio))
                    .addGroup(PanelAPTLayout.createSequentialGroup()
                        .addGroup(PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52))
        );
        PanelAPTLayout.setVerticalGroup(
            PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAPTLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(PanelAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ComboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTRif, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboMunicipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboEstados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(227, 227, 227))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AC1)
                                    .addComponent(AC3)
                                    .addComponent(AC7)
                                    .addComponent(AC9)
                                    .addComponent(AC5))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AC4)
                                    .addComponent(AC2)
                                    .addComponent(AC6)
                                    .addComponent(AC8)
                                    .addComponent(AC10))))
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BtnFinalizar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(PanelAPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(533, 533, 533)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(BtnFinalizar))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AC1)
                                            .addComponent(AC2))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AC3)
                                            .addComponent(AC4))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AC5)
                                            .addComponent(AC6))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AC7)
                                            .addComponent(AC8))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(AC9)
                                            .addComponent(AC10))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(PanelAPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(TXTRif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(ComboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(56, 56, 56))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JOptionPane.showMessageDialog(rootPane,"Todos los cambios no guardados han sido borrados.");
        try {
            VentanaMenuPrincipal cambio = new VentanaMenuPrincipal();
            cambio.setVisible(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMenuEdificio.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ComboEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboEstadosMouseClicked
/*
        int fk = ComboEstados.getSelectedIndex();
        fk++;
        ComboMunicipio.removeAllItems();
        try{
            VentanaMenuEdificioControlador.llenarListaMunicipios(Integer.toString(fk));
                for (String x: VentanaMenuEdificioControlador.Municipios){
                    ComboMunicipio.addItem(x);
                }
            
            
            }catch(Exception e){}
    */    // TODO add your handling code here:
    }//GEN-LAST:event_ComboEstadosMouseClicked

    private void ComboEstadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboEstadosMouseReleased

       if (ActivaCombo){
        
        int fk = ComboEstados.getSelectedIndex();
        fk++;
        ClaveEstado =Integer.toString(fk);
        ComboMunicipio.removeAllItems();
        try{
            VentanaMenuEdificioControlador.llenarListaMunicipios(ClaveEstado);
                for (String x: VentanaMenuEdificioControlador.Municipios){
                    ComboMunicipio.addItem(x);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"Error al llenar lista municipios ->"+e);
            }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboEstadosMouseReleased

    private void BtnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalizarActionPerformed

          if (Opcion == 0){
                    String ParroquiaSeleccionada = (String) ComboParroquia.getSelectedItem();
                    try {
                              String NombreEdif = TXTNombre.getText();
                              String RifEdif = TXTRif.getText();
                              //JOptionPane.showMessageDialog(rootPane, "Logro buscar la clave de parroquia y es:"+ClaveParroquia);
                              ClaveParroquia = Util.Consultar_PKPorNombreParroquia("LUGAR","LUG_CLAVE",ParroquiaSeleccionada,"LUG_NOMBRE",ClaveMunicipio);
                              //JOptionPane.showMessageDialog(rootPane, "Logro buscar la clave de parroquia y es:"+ClaveParroquia);
                              VentanaMenuEdificioControlador.InsertarEdificioSQL(RifEdif,NombreEdif,ClaveParroquia);
                              String ClaveEdificio =Util.Consultar_PK("EDIFICIO","EDI_CLAVE");
                              int claveedificio = Integer.parseInt(ClaveEdificio);
                              JOptionPane.showMessageDialog(rootPane,"EDIFICIO: "+NombreEdif+" AGREGADO SATISFACTORIAMENTE");

                              AreaValida=false;
                              AreasComunes.clear();
                              if (AC1.isSelected()){
                                        AreaValida = true;
                                         AreasComunes.add("1");
                               }
                              if (AC2.isSelected()){
                                         AreaValida = true;
                                         AreasComunes.add("2");
                              }
                              if (AC3.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("3");
                              }
                              if (AC4.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("4");
                              }
                              if (AC5.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("5");
                               }
                              if (AC6.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("6");
                               }
                              if (AC7.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("7");
                               }
                              if (AC8.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("8");
                              }if (AC9.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("9");
                              }if (AC10.isSelected()){
                                        AreaValida = true;
                                        AreasComunes.add("10");
                              }
            
                              String cantidad = txtCantidad.getText();
                              String medidas = txtMedidas.getText();
                              int Cantidad = Integer.parseInt(cantidad);
                              VentanaMenuApartamentoControlador.InsertaAPTSQL(medidas);
                              String ClaveAPT = Util.Consultar_PK("APARTAMENTO", "APT_CLAVE");
                              float ali = 100 / Cantidad;
                              String precio = txtprecio.getText();
                              float precio2 = Float.parseFloat(precio);
                              for (int piso = 1, j = piso + 1; piso <= Cantidad ;piso++){
                              
                                         VentanaMenuApartamentoControlador.InsertaAPT_DETSQL(ali,ClaveEdificio, ClaveAPT,"SI",Integer.toString(piso),precio2);
                                         //System.out.println("piso ->"+piso);
                              }
                              //JOptionPane.showMessageDialog(rootPane,"LA CLAVE APT ES:"+ClaveAPT);
                              VentanaMenuEdificioControlador.InsertaArea_DetSQL(claveedificio);
                              VentanaMenuEdificio refresh = new VentanaMenuEdificio();
                              refresh.setVisible(true);
                              this.dispose();
                              
                              
                              
                    }catch(Exception e){
                              JOptionPane.showMessageDialog(rootPane,"ERROR EN EJECUTAR CONSULTA1 ->"+e);
                    }
          }
    }//GEN-LAST:event_BtnFinalizarActionPerformed

    private void ComboMunicipioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboMunicipioMouseReleased

           if (ActivaCombo)
           {            String MunicipioSeleccionado = (String) ComboMunicipio.getSelectedItem();
            ComboParroquia.removeAllItems();
            //AQUI TENGO EL NOMBRE DEL MUNICIPIO
            //NECESITO LA CLAVE DE ESE MUNICIPIO (DEPENDIENDO DE EL ESTADO LO TENGO EN LA VARIABLE CLAVE ESTADO)
            try {
            ClaveMunicipio = Util.Consultar_PKPorNombreMunicipios("LUGAR","LUG_CLAVE",MunicipioSeleccionado,"LUG_NOMBRE",ClaveEstado);
            VentanaMenuEdificioControlador.llenarListaParroquias(ClaveMunicipio);    
            for (String x :VentanaMenuEdificioControlador.Parroquias ){
                    ComboParroquia.addItem(x);
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMenuEdificio.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
    }//GEN-LAST:event_ComboMunicipioMouseReleased

    private void ComboMunicipioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboMunicipioMouseEntered

    }//GEN-LAST:event_ComboMunicipioMouseEntered

        public static void LimpiarJTable(){
          int a =modelo.getRowCount()-1;
          for(int i=a;i>=0;i--){ 
                    modelo.removeRow(i);
          }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

             Opcion = ComboOpcion.getSelectedIndex();
                if (Opcion==0){
                        ActivaCombo = true;
                        ComboEstados.setVisible(true);
                        ComboMunicipio.setVisible(true);
                        ComboParroquia.setVisible(true);
                        ComboEstados.setEnabled(true);
                        ComboParroquia.setEnabled(true);
                        ComboMunicipio.setEnabled(true);
                        jLabel3.setVisible(true);
                        jLabel4.setVisible(true);
                        jLabel5.setVisible(true);
                        jLabel6.setVisible(true);
                        jLabel7.setVisible(true);
                        jLabel8.setVisible(true);
                        jLabel9.setVisible(true);
                        jLabel12.setVisible(true);
                        jLabel13.setVisible(true);
                        AC1.setVisible(true);
                        AC2.setVisible(true);
                        AC3.setVisible(true);
                        AC4.setVisible(true);
                        AC5.setVisible(true);
                        AC6.setVisible(true);
                        AC7.setVisible(true);
                        AC8.setVisible(true);
                        AC9.setVisible(true);
                         AC10.setVisible(true);
                         Tabla.setVisible(true);
                       ComboEstados.setVisible(true);
                       ComboMunicipio.setVisible(true);
                       ComboParroquia.setVisible(true);
                       TXTNombre.setVisible(true);
                       TXTRif.setVisible(true);
                      // btnAyuda.setVisible(true);
                       PanelAPT.setVisible(true);
                       BtnFinalizar.setText("Registrar Edificio");
                       JOptionPane.showMessageDialog(rootPane,"A CONTINUACION RELLENE TODOS LOS CAMPOS");
                       jLabel5.setText(("Especifique la direccion del Edifcio"));
                       LimpiarJTable();
                    try{
                              VentanaMenuEdificioControlador.RellenaTablaSQL();
                              VentanaMenuEdificioControlador.LlenarEstado();
                    }catch (Exception e){
                              JOptionPane.showMessageDialog(rootPane,"REVENTO EN ->"+e);
                    }
                    for (String x: VentanaMenuEdificioControlador.Estados){
                              ComboEstados.addItem(x);
                    }
          
                }
                if (Opcion==1){
                    PanelAPT.setVisible(false);
                           
                    ActivaCombo=false;
                        jLabel5.setText("Direccion Especifica del edificio seleccionado");
                        ComboEstados.setVisible(true);
                        ComboMunicipio.setVisible(true);
                        ComboParroquia.setVisible(true);
                        jLabel3.setVisible(true);
                        jLabel4.setVisible(true);
                        jLabel5.setVisible(true);
                        jLabel6.setVisible(true);
                        jLabel7.setVisible(true);
                        jLabel8.setVisible(true);
                        jLabel9.setVisible(true);
                        jLabel12.setVisible(true);
                        jLabel13.setVisible(true);
                        AC1.setVisible(true);
                        AC2.setVisible(true);
                        AC3.setVisible(true);
                        AC4.setVisible(true);
                        AC5.setVisible(true);
                        AC6.setVisible(true);
                        AC7.setVisible(true);
                        AC8.setVisible(true);
                        AC9.setVisible(true);
                        AC10.setVisible(true);
                        Tabla.setVisible(true);
                       ComboEstados.setVisible(true);
                       ComboMunicipio.setVisible(true);
                       ComboParroquia.setVisible(true);
                       TXTNombre.setVisible(true);
                       TXTRif.setVisible(true);
                       //btnAyuda.setVisible(true);
                       BtnFinalizar.setText("Registrar Edificio");
                       JOptionPane.showMessageDialog(rootPane,"En la tabla aparece la informacion general de cada edificio, si desea "
                               + "informacion detallada haga click sobre alguna fila..");
                       ComboEstados.removeAll();
                        ComboParroquia.removeAll();
                        ComboMunicipio.removeAll();
                        ComboEstados.addItem("Estado");
                        ComboMunicipio.addItem("Municipio");
                        ComboParroquia.addItem("Parroquia");
                        ComboEstados.setEnabled(false);
                        ComboMunicipio.setEnabled(false);
                        ComboParroquia.setEnabled(false);
                        PermisosActuales.clear();
                        LimpiarJTable();
                    try{
                              VentanaMenuEdificioControlador.RellenaTablaSQL();
                              VentanaMenuEdificioControlador.LlenarEstado();
                    }catch (Exception e){
                              JOptionPane.showMessageDialog(rootPane,"REVENTO EN ->"+e);
                    }
                    for (String x: VentanaMenuEdificioControlador.Estados){
                              ComboEstados.addItem(x);
                    }
          
                }
                
          if (Opcion==2){
                        PanelAPT.setVisible(false);
                       
                        ActivaCombo=true;
                        jLabel5.setText("Direccion Especifica del edificio a Editar");
                        ComboEstados.setVisible(true);
                        ComboMunicipio.setVisible(true);
                        ComboParroquia.setVisible(true);
                        jLabel3.setVisible(true);
                        jLabel4.setVisible(true);
                        jLabel5.setVisible(true);
                        jLabel6.setVisible(true);
                        jLabel7.setVisible(true);
                        jLabel8.setVisible(true);
                        jLabel9.setVisible(true);
                        jLabel12.setVisible(true);
                        jLabel13.setVisible(true);
                        AC1.setVisible(true);
                        AC2.setVisible(true);
                        AC3.setVisible(true);
                        AC4.setVisible(true);
                        AC5.setVisible(true);
                        AC6.setVisible(true);
                        AC7.setVisible(true);
                        AC8.setVisible(true);
                        AC9.setVisible(true);
                        AC10.setVisible(true);
                        Tabla.setVisible(true);
                       ComboEstados.setVisible(true);
                       ComboMunicipio.setVisible(true);
                       ComboParroquia.setVisible(true);
                       TXTNombre.setVisible(true);
                       TXTRif.setVisible(true);
                       //btnAyuda.setVisible(true);
                       BtnFinalizar.setText("Modificar Edificio");
                       ComboEstados.removeAll();
                        ComboParroquia.removeAll();
                        ComboMunicipio.removeAll();
                        ComboEstados.setEnabled(true);
                        ComboMunicipio.setEnabled(true);
                        ComboParroquia.setEnabled(true);
                        PermisosActuales.clear();
                    LimpiarJTable();
                    try{
                              VentanaMenuEdificioControlador.RellenaTablaSQL();
                              VentanaMenuEdificioControlador.LlenarEstado();
                    }catch (Exception e){
                              JOptionPane.showMessageDialog(rootPane,"REVENTO EN ->"+e);
                    }
                    for (String x: VentanaMenuEdificioControlador.Estados){
                              ComboEstados.addItem(x);
                    }
          
          }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaKeyReleased

    }//GEN-LAST:event_TablaKeyReleased

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        
          if( ( Tabla.getSelectedRows().length > 0 ) && ((Opcion == 1)) ) {
                        
                    int num = Tabla.getSelectedRow();
                    String nomb=(String)Tabla.getValueAt(num,1);
                    String rif =(String)Tabla.getValueAt(num,0);
                    String ClaveParroquia=(String)Tabla.getValueAt(num, 2);
                    this.TXTNombre.setText(nomb);
                    this.TXTRif.setText(rif);
                    String Direccion = "";
                    
                    try {
                              Direccion = devuelvedireccionSQL(ClaveParroquia);
                              String[] DireccionDesglosada = Direccion.split("/");
                              ComboEstados.removeAllItems();
                              ComboMunicipio.removeAllItems();
                              ComboParroquia.removeAllItems();
                              ComboEstados.addItem(DireccionDesglosada[0]);
                              ComboMunicipio.addItem(DireccionDesglosada[1]);
                              ComboParroquia.addItem(DireccionDesglosada[2]);
                              ComboEstados.setSelectedIndex(0);
                              ComboMunicipio.setSelectedIndex(0);
                              ComboParroquia.setSelectedIndex(0);
                              AC1.setSelected(false);
                              AC2.setSelected(false);
                              AC3.setSelected(false);
                              AC4.setSelected(false);
                              AC5.setSelected(false);
                              AC6.setSelected(false);
                              AC7.setSelected(false);
                              AC8.setSelected(false);
                              AC9.setSelected(false);
                              AC10.setSelected(false);
                              PermisosActuales.clear();
                              VentanaMenuEdificioControlador.ConsultaClaveEdificioSeleccionadoSQL(nomb, rif);
                              for (String x : PermisosActuales){
                                        if (x.equalsIgnoreCase("1")){
                                                  AC1.setSelected(true);
                                        }if (x.equalsIgnoreCase("2")){
                                                  AC2.setSelected(true);
                                        }if (x.equalsIgnoreCase("3")){
                                                  AC3.setSelected(true);
                                        }if (x.equalsIgnoreCase("4")){
                                                  AC4.setSelected(true);
                                        }if (x.equalsIgnoreCase("5")){
                                                  AC5.setSelected(true);
                                        }if (x.equalsIgnoreCase("6")){
                                                  AC6.setSelected(true);
                                        }if (x.equalsIgnoreCase("7")){
                                                  AC7.setSelected(true);
                                        }if (x.equalsIgnoreCase("8")){
                                                  AC8.setSelected(true);
                                        }if (x.equalsIgnoreCase("9")){
                                                  AC9.setSelected(true);
                                        }if (x.equalsIgnoreCase("10")){
                                                  AC10.setSelected(true);
                                        }    
                              }                  
                    }catch (SQLException ex) {
                              Logger.getLogger(VentanaMenuEdificio.class.getName()).log(Level.SEVERE, null, ex);
                    }
          }
          if( ( Tabla.getSelectedRows().length > 0 ) && ((Opcion == 2)) ) {
                        
                    int num = Tabla.getSelectedRow();
                    String nomb=(String)Tabla.getValueAt(num,1);
                    String rif =(String)Tabla.getValueAt(num,0);
                    String ClaveParroquia=(String)Tabla.getValueAt(num, 2);
                    this.TXTNombre.setText(nomb);
                    this.TXTRif.setText(rif);
                    String Direccion = "";
                    
                    try {
                              Direccion = devuelvedireccionSQL(ClaveParroquia);
                              String[] DireccionDesglosada = Direccion.split("/");
                              ComboEstados.removeAllItems();
                              ComboMunicipio.removeAllItems();
                              ComboParroquia.removeAllItems();
                              ComboEstados.addItem(DireccionDesglosada[0]);
                              ComboMunicipio.addItem(DireccionDesglosada[1]);
                              ComboParroquia.addItem(DireccionDesglosada[2]);
                              ComboEstados.setSelectedIndex(0);
                              ComboMunicipio.setSelectedIndex(0);
                              ComboParroquia.setSelectedIndex(0);
                              AC1.setSelected(false);
                              AC2.setSelected(false);
                              AC3.setSelected(false);
                              AC4.setSelected(false);
                              AC5.setSelected(false);
                              AC6.setSelected(false);
                              AC7.setSelected(false);
                              AC8.setSelected(false);
                              AC9.setSelected(false);
                              AC10.setSelected(false);
                              PermisosActuales.clear();
                              VentanaMenuEdificioControlador.ConsultaClaveEdificioSeleccionadoSQL(nomb, rif);
                              for (String x : PermisosActuales){
                                        if (x.equalsIgnoreCase("1")){
                                                  AC1.setSelected(true);
                                        }if (x.equalsIgnoreCase("2")){
                                                  AC2.setSelected(true);
                                        }if (x.equalsIgnoreCase("3")){
                                                  AC3.setSelected(true);
                                        }if (x.equalsIgnoreCase("4")){
                                                  AC4.setSelected(true);
                                        }if (x.equalsIgnoreCase("5")){
                                                  AC5.setSelected(true);
                                        }if (x.equalsIgnoreCase("6")){
                                                  AC6.setSelected(true);
                                        }if (x.equalsIgnoreCase("7")){
                                                  AC7.setSelected(true);
                                        }if (x.equalsIgnoreCase("8")){
                                                  AC8.setSelected(true);
                                        }if (x.equalsIgnoreCase("9")){
                                                  AC9.setSelected(true);
                                        }if (x.equalsIgnoreCase("10")){
                                                  AC10.setSelected(true);
                                        }    
                              }                  
                    }catch (SQLException ex) {
                              Logger.getLogger(VentanaMenuEdificio.class.getName()).log(Level.SEVERE, null, ex);
                    }
          }
          
          

        
// TODO add your handling code here:
    }//GEN-LAST:event_TablaMouseClicked

    private void AC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AC6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ComboParroquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboParroquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboParroquiaActionPerformed

    public void cargarInterfaz(){
        String x[][]={};
        String columnas[]={"Rif","Nombre","Direccion"};
        modelo = new DefaultTableModel(x, columnas);
        Tabla.setModel(modelo);
        //RellenaTablaSQL();
    }

    public static void RellenarAreasComunes(){
        
            
        
        
    
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaMenuEdificio().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaMenuEdificio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AC1;
    private javax.swing.JCheckBox AC10;
    private javax.swing.JCheckBox AC2;
    private javax.swing.JCheckBox AC3;
    private javax.swing.JCheckBox AC4;
    private javax.swing.JCheckBox AC5;
    private javax.swing.JCheckBox AC6;
    private javax.swing.JCheckBox AC7;
    private javax.swing.JCheckBox AC8;
    private javax.swing.JCheckBox AC9;
    private javax.swing.JButton BtnFinalizar;
    private javax.swing.JComboBox ComboEstados;
    private javax.swing.JComboBox ComboMunicipio;
    private javax.swing.JComboBox ComboOpcion;
    private javax.swing.JComboBox ComboParroquia;
    private javax.swing.JPanel PanelAPT;
    private javax.swing.JTextField TXTNombre;
    private javax.swing.JTextField TXTRif;
    private javax.swing.JTable Tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMedidas;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
