/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.VentanaUsuarioControlador;
import Modelo.ConexionOracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jesus Trejo
 */
public class VentanaMenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuUsuario
     */
    
    
    public VentanaMenuUsuario() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconbuil.png")).getImage() );
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/fondo1.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());    

        VentanaUsuarioControlador.initOutlets(Combo);
        VentanaUsuarioControlador.LlenarComboBoxSQL();
        PASS1.setEnabled(false);
        PASS2.setEnabled(false);
        BTNRegistrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LBLTitulo = new javax.swing.JLabel();
        BTNVolver = new javax.swing.JButton();
        BTNRegistrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LBLUsuario = new javax.swing.JLabel();
        TXTUsuario = new javax.swing.JTextField();
        BTNVerificar = new javax.swing.JButton();
        LBLRol = new javax.swing.JLabel();
        LBLPass1 = new javax.swing.JLabel();
        PASS1 = new javax.swing.JPasswordField();
        LBLPass2 = new javax.swing.JLabel();
        PASS2 = new javax.swing.JPasswordField();
        Combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        LBLRol2 = new javax.swing.JLabel();
        LBLRol1 = new javax.swing.JLabel();
        BTNROL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        LBLTitulo.setText("Registro De Usuario");

        BTNVolver.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BTNVolver.setText("Volver");
        BTNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolverActionPerformed(evt);
            }
        });

        BTNRegistrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BTNRegistrar.setText("Registrar Usuario");
        BTNRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRegistrarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulario Para usuario"));

        LBLUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLUsuario.setText("Nombre De usuario");

        TXTUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        TXTUsuario.setText("Usuario");

        BTNVerificar.setFont(new java.awt.Font("Comic Sans MS", 2, 10)); // NOI18N
        BTNVerificar.setText("Verificar Usuario");
        BTNVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVerificarActionPerformed(evt);
            }
        });

        LBLRol.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLRol.setText("Seleccione el rol que desea que tenga el usuario");

        LBLPass1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLPass1.setText("Contraseña");

        PASS1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PASS1.setText("1");
        PASS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASS1ActionPerformed(evt);
            }
        });

        LBLPass2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLPass2.setText("Repita la Contraseña");

        PASS2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PASS2.setText("1");

        Combo.setEditable(true);
        Combo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLUsuario)
                    .addComponent(LBLPass1)
                    .addComponent(LBLPass2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PASS2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TXTUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(PASS1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLRol))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(BTNVerificar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLUsuario)
                    .addComponent(TXTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNVerificar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLPass1)
                    .addComponent(PASS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLRol))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLPass2)
                    .addComponent(PASS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones Para Rol"));

        LBLRol2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLRol2.setText("Crear un rol si es de su agrado");

        LBLRol1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        LBLRol1.setText("Si el rol deseado no se encuentra en la lista, puede ");

        BTNROL.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BTNROL.setText("Crear Rol");
        BTNROL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNROLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLRol2)
                    .addComponent(LBLRol1))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNROL)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LBLRol1)
                .addGap(18, 18, 18)
                .addComponent(LBLRol2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(BTNROL)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNRegistrar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LBLTitulo)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LBLTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNRegistrar)
                    .addComponent(BTNVolver))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void BTNVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVerificarActionPerformed

        try{
            boolean disponible = VentanaUsuarioControlador.CompruebaUsuarioDisponibleSQL(TXTUsuario.getText());
            if (disponible){
                JOptionPane.showMessageDialog(rootPane,"EL USUARIO "+TXTUsuario.getText()+" SE ENCUENTRA DISPONIBLE");
                TXTUsuario.setEditable(false);
                BTNVerificar.setEnabled(false);
                PASS1.setEnabled(true);
                PASS2.setEnabled(true);
                BTNRegistrar.setEnabled(true);
            }
            else
                JOptionPane.showMessageDialog(rootPane,"ERROR, EL USUARIO "+TXTUsuario.getText()+" NO SE ENCUENTRA DISPONIBLE");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"ERROR, DEBE INGRESAR ALGUN USUARIO");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNVerificarActionPerformed

    private void BTNROLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNROLActionPerformed
        try {
            VentanaMenuRoles Auxiliar = new VentanaMenuRoles();
            Auxiliar.setVisible(true);
            this.dispose();
            
           
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNROLActionPerformed

    private void BTNRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegistrarActionPerformed

         try{
            if (PASS1.getText().equals(PASS2.getText())){
                String UsuarioSQL = TXTUsuario.getText();
                String PassSQL = PASS2.getText();
                //int rol = Combo.getSelectedIndex();
                //JOptionPane.showMessageDialog(rootPane,"EL ROL DEBERIA SER 1 PERO ES -> "+Integer.toHexString(rol));
                String rol = (String) Combo.getSelectedItem();
                //JOptionPane.showMessageDialog(rootPane,"EL ROL  ES -> "+pba);
                String rol2 = rol;
                VentanaUsuarioControlador.InsertaUsuarioBD(UsuarioSQL,PassSQL,rol2);
                //JOptionPane.showMessageDialog(rootPane,"USUARIO CREADO CORRECTAMENTE");
                VentanaMenuPrincipal nuevo = new VentanaMenuPrincipal();
                nuevo.setVisible(true);
                this.dispose();
                
                
                
            }
            else{
            JOptionPane.showMessageDialog(rootPane,"ERROR, las contraseñas no coinciden.");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"ERROR, CONSULTA SQL. EN ->"+e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNRegistrarActionPerformed

    private void PASS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASS1ActionPerformed

    private void BTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolverActionPerformed

         VentanaMenuPrincipal nuevo = null;
        try {
            nuevo = new VentanaMenuPrincipal();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaMenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
         nuevo.setVisible(true);
         this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaMenuUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaMenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNROL;
    private javax.swing.JButton BTNRegistrar;
    private javax.swing.JButton BTNVerificar;
    private javax.swing.JButton BTNVolver;
    private javax.swing.JComboBox Combo;
    private javax.swing.JLabel LBLPass1;
    private javax.swing.JLabel LBLPass2;
    private javax.swing.JLabel LBLRol;
    private javax.swing.JLabel LBLRol1;
    private javax.swing.JLabel LBLRol2;
    private javax.swing.JLabel LBLTitulo;
    private javax.swing.JLabel LBLUsuario;
    private javax.swing.JPasswordField PASS1;
    private javax.swing.JPasswordField PASS2;
    private javax.swing.JTextField TXTUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
