/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.VentanaMenuFondosControlador;
import static Interfaz.VentanaMenuJuntaCondominio.Opcion;
import Modelo.Util;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class VentanaMenuFondos extends javax.swing.JFrame {

    public static int Opcion=0;
    public static int cont2=0;
     public static int cont3=0;
     public static int cont4=0;
    public static int ClaveContrato=0;
    public static int ContadorTabla=0;
    public static int contadorTransferencia=0;
    public static int ColumnaElegida=0;
    public static float MontoFondoEmisor=0;
    public static int ClaveFondoEmisor;
    public static int ClaveFondoReceptor;
    public static boolean salir=false;
     public static DefaultTableModel modeloEdificios = new DefaultTableModel();
     public static DefaultTableModel modeloContratos = new DefaultTableModel();
     public static DefaultTableModel modeloFondos = new DefaultTableModel();
      public static ArrayList IdentificacionesOficinas = new ArrayList();
     public static String ClaveEdificio="";
     public static String NombreEdificio="";
     
    /**
     * Creates new form VentanaMenuFondos
     */
    public VentanaMenuFondos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconbuil.png")).getImage() );
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/fondo2.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight()); 
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        BTNAtras.setVisible(true);
        TXTFondoEmisor.setText("");
        TXTFondoReceptor.setText("");
        Panel3.setVisible(false);
        BTNSeleccionTransferencia.setVisible(false);
        ContadorTabla=0;
        TXTFondoEmisor.setEnabled(false);
        TXTFondoReceptor.setEnabled(false);
    }
    
    
     public static void LimpiarJTable(DefaultTableModel Nombremodelo){
          int a =Nombremodelo.getRowCount()-1;
          for(int i=a;i>=0;i--){ 
                    Nombremodelo.removeRow(i);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        BTNReset = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        Label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNAtras = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        TXTFondoEmisor = new javax.swing.JTextField();
        TXTFondoReceptor = new javax.swing.JTextField();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        BTNTransferencia = new javax.swing.JButton();
        TXTMontoTransferir = new javax.swing.JTextField();
        Label6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BTNSeleccionTransferencia = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ComboBox1 = new javax.swing.JComboBox();
        SeleccionCombo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        BTNReset.setText("Reset");
        BTNReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetActionPerformed(evt);
            }
        });

        Label1.setText("Seleccione el Edificio para consultar su fondo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNReset, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNReset)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Menu Fondos");

        BTNAtras.setText("Volver");
        BTNAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAtrasActionPerformed(evt);
            }
        });

        Panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel3.setOpaque(false);

        Label4.setText("Fondo Emisor");

        Label5.setText("Fondo Receptor");

        BTNTransferencia.setText("Transferir");
        BTNTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTransferenciaActionPerformed(evt);
            }
        });

        Label6.setText("Monto a Transferir");

        jButton1.setText("Resetear Proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTFondoEmisor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                        .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTFondoReceptor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                        .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BTNTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(TXTMontoTransferir))
                        .addContainerGap())))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTFondoReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTFondoEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label4)
                    .addComponent(Label5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTMontoTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label6)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(BTNTransferencia)
                .addContainerGap())
        );

        BTNSeleccionTransferencia.setText("Transferencia");
        BTNSeleccionTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSeleccionTransferenciaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione la Opcion que Desea Realizar"));
        jPanel3.setToolTipText("");
        jPanel3.setOpaque(false);

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consultar Fondo", "Transferencia de Fondos" }));

        SeleccionCombo.setText("Seleccionar");
        SeleccionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(SeleccionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionCombo))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTNSeleccionTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addComponent(BTNSeleccionTransferencia)
                .addGap(117, 117, 117)
                .addComponent(BTNAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionComboActionPerformed
        // TODO add your handling code here:
    Opcion = ComboBox1.getSelectedIndex();
        if (Opcion == 0){
            jPanel1.setVisible(true);
            jPanel2.setVisible(false);
            Panel3.setVisible(false);
            BTNSeleccionTransferencia.setVisible(false);
            Label1.setText("Seleccione el Edificio a Consultar");
            ContadorTabla=1;
            LimpiarJTable(modeloEdificios);
            cargarInterfazEdificios();
            
            try {
                VentanaMenuFondosControlador.RellenaTablaSQL();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
            }   
            
            
        }
        
        
        if(Opcion==1){ //Transferencias entre fondos de un mismo edificio
            jPanel1.setVisible(true);
            Label1.setText("Seleccione el Edificio");
            ContadorTabla=1;
            contadorTransferencia=0;
            ColumnaElegida=0;
            LimpiarJTable(modeloEdificios);
            cargarInterfazEdificios();
            
            try {
                VentanaMenuFondosControlador.RellenaTablaSQL();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
            }   
            
        }
        
    }//GEN-LAST:event_SeleccionComboActionPerformed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
        // TODO add your handling code here:
        
   
               if(Opcion==0 && ContadorTabla==1){
              if( ( Tabla1.getSelectedRows().length > 0 ) && (Opcion == 0) ) {
                int num = Tabla1.getSelectedRow();
                 String rif = (String) Tabla1.getValueAt(num,0);
                 NombreEdificio = (String) Tabla1.getValueAt(num,1);

                    LimpiarJTable(modeloContratos);
                    cargarInterfazContratos();
                    
                  try {
                     ClaveEdificio = Util.Consultar_PK_EdificioConRif(rif);
                     VentanaMenuFondosControlador.RellenaTablaContratosSQL(ClaveEdificio);
                     Label1.setText("Seleccione el contrato a consultar");
                     ContadorTabla++;
                  } catch (SQLException ex) {
                      Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  
                  
                }
              
              }
               if (Opcion==0 && ContadorTabla==2){
                   if( ( Tabla1.getSelectedRows().length > 0 ) && (Opcion == 0) ) {
                int num = Tabla1.getSelectedRow();
                ClaveContrato = Integer.parseInt((String) Tabla1.getValueAt(num,0));
                       LimpiarJTable(modeloFondos);
                       cargarInterfazFondos();
                        try {
                     
                     VentanaMenuFondosControlador.RellenaTablaFondosSQL(ClaveContrato);
                     jPanel2.setVisible(true);
                     Label2.setText("Edificio = >"+NombreEdificio+"<");
                     ContadorTabla=0;
                  } catch (SQLException ex) {
                      Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
                  }
                 
                   
               }
                   
             }
               
               
               
               //Transferencia
               
               if(Opcion==1 && ContadorTabla==1){
              if( ( Tabla1.getSelectedRows().length > 0 ) && (Opcion == 1) ) {
                int num = Tabla1.getSelectedRow();
                 String rif = (String) Tabla1.getValueAt(num,0);
                 NombreEdificio = (String) Tabla1.getValueAt(num,1);

                    LimpiarJTable(modeloContratos);
                    cargarInterfazContratos();
                    
                  try {
                     ClaveEdificio = Util.Consultar_PK_EdificioConRif(rif);
                     VentanaMenuFondosControlador.RellenaTablaContratosSQL(ClaveEdificio);
                     Label1.setText("Seleccione el contrato");
                     ContadorTabla++;
                  } catch (SQLException ex) {
                      Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  
                  
                }
              
              }
               if (Opcion==1 && ContadorTabla==2){
                   if( ( Tabla1.getSelectedRows().length > 0 ) && (Opcion == 1) ) {
                int num = Tabla1.getSelectedRow();
                 ClaveContrato = Integer.parseInt((String) Tabla1.getValueAt(num,0));
                       LimpiarJTable(modeloFondos);
                       cargarInterfazFondos();
                        try {
                     
                     VentanaMenuFondosControlador.RellenaTablaFondosSQL(ClaveContrato);
                     jPanel2.setVisible(true);
                     Label2.setText("Edificio = >"+NombreEdificio+"<");
                     BTNSeleccionTransferencia.setVisible(true);
                     Tabla2.setEnabled(false);
                     jPanel2.setEnabled(false);
                     ContadorTabla=0;
                  } catch (SQLException ex) {
                      Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
                  }
                 
                   
               }
                   
             }
    }//GEN-LAST:event_Tabla1MouseClicked

    private void BTNResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetActionPerformed
        // TODO add your handling code here:
         if (Opcion == 0){
            ContadorTabla=1;
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            Panel3.setVisible(false);
            BTNSeleccionTransferencia.setVisible(false);
            LimpiarJTable(modeloEdificios);
            cargarInterfazEdificios();
            jPanel2.setVisible(false);
            Label1.setText("Seleccione el Edificio a Consultar");
            
            try {
                VentanaMenuFondosControlador.RellenaTablaSQL();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
            }   
            
            
        }
               if (Opcion == 1){
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
            Panel3.setVisible(false);
            BTNSeleccionTransferencia.setVisible(false);
            Label1.setText("Seleccione el Edificio a Consultar");
            ContadorTabla=1;
            
            try {
                VentanaMenuFondosControlador.RellenaTablaSQL();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
            }   
            
            
        }
    }//GEN-LAST:event_BTNResetActionPerformed

    private void BTNAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAtrasActionPerformed
 try {
        VentanaMenuPrincipal nuevo  = new VentanaMenuPrincipal();
        nuevo.setVisible(true);
        this.dispose();
    } catch (SQLException ex) {
          JOptionPane.showMessageDialog(rootPane,"ERROR, debe ingresar desde el LOG-IN para cargar los permisos");
           //Logger.getLogger(VentanaGenerarContrato.class.getName()).log(Level.SEVERE, null, ex);
    }        // TODO add your handling code here:
        
    }//GEN-LAST:event_BTNAtrasActionPerformed

    private void BTNSeleccionTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSeleccionTransferenciaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Por favor Seleccione en la Tabla el fondo Emisor");
        Panel3.setVisible(true);
        jPanel1.setEnabled(false);
        Tabla2.setEnabled(true);
        BTNSeleccionTransferencia.setVisible(false);
        
    }//GEN-LAST:event_BTNSeleccionTransferenciaActionPerformed

    private void Tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla2MouseClicked
        // TODO add your handling code here:
           
        
         if (Opcion==1 && contadorTransferencia==0){
                   if( ( Tabla2.getSelectedRows().length > 0 ) && (Opcion == 1) ) {
                int num = Tabla2.getSelectedRow();
                ColumnaElegida=num;
                 String FondoEmisor = (String) Tabla2.getValueAt(num,1);
                 MontoFondoEmisor= (float) Tabla2.getValueAt(num, 2);
                 ClaveFondoEmisor=Integer.parseInt((String) Tabla2.getValueAt(num, 0));
                 TXTFondoEmisor.setText(FondoEmisor);
                 contadorTransferencia++;
              
 JOptionPane.showMessageDialog(rootPane,"Por favor Seleccione en la Tabla el fondo Receptor");
                   }
         }
           if (Opcion==1 && contadorTransferencia==1 ){
               
                   if( ( Tabla2.getSelectedRows().length > 0 ) && (Opcion == 1) ) {
                int num1 = Tabla2.getSelectedRow();
                
                if(num1 ==ColumnaElegida ){
                    JOptionPane.showMessageDialog(rootPane,"Se ha Elejido el mismo Fondo,Por Favor Elija otro Fondo receptor");
                }
                else{
                    String FondoReceptor = (String) Tabla2.getValueAt(num1,1);
                    ClaveFondoReceptor= Integer.parseInt((String) Tabla2.getValueAt(num1, 0));
                 TXTFondoReceptor.setText(FondoReceptor);
                 contadorTransferencia++;

                 
                    
                }
               
                 
                   }
         }
        
    }//GEN-LAST:event_Tabla2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TXTFondoEmisor.setText("");
        TXTFondoReceptor.setText("");
        TXTMontoTransferir.setText("");
        contadorTransferencia=0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTransferenciaActionPerformed
        // TODO add your handling code here:
        if(TXTMontoTransferir.getText().equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(rootPane,"Debe Indicar un Monto de transferencia");    
        }
        else{
            int MontoTransferir = Integer.parseInt(TXTMontoTransferir.getText());
            
            if(MontoTransferir > MontoFondoEmisor){
                JOptionPane.showMessageDialog(rootPane,"El monto a transferir es mayor al que contiene el fondo emisor");
            }
            else
            {
                try {
                    VentanaMenuFondosControlador.RestarAlFondoEmisorSQL(MontoTransferir,ClaveContrato,ClaveFondoEmisor);
                    VentanaMenuFondosControlador.SumarAlFondoReceptorSQL(MontoTransferir,ClaveContrato,ClaveFondoReceptor);
                    JOptionPane.showMessageDialog(rootPane,"Los Fondos Fueron Actualizados");
                      VentanaMenuFondos VMF = new VentanaMenuFondos();
                        VMF.setVisible(true);
                        this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaMenuFondos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_BTNTransferenciaActionPerformed

    
     public void cargarInterfazEdificios (){
         String x[][]={};
        String columnas[]={"RIF","Nombre"};
        modeloEdificios = new DefaultTableModel(x, columnas);
        Tabla1.setModel(modeloEdificios);
    }
      public void cargarInterfazContratos (){
         String x[][]={};
        String columnas[]={"ID Contrato","Oficina"};
        modeloContratos = new DefaultTableModel(x, columnas);
        Tabla1.setModel(modeloContratos);
    }
      public void cargarInterfazFondos (){
         String x[][]={};
        String columnas[]={"ID","Tipo","Monto Restante"};
        modeloFondos = new DefaultTableModel(x, columnas);
        Tabla2.setModel(modeloFondos);
    }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuFondos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuFondos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAtras;
    private javax.swing.JButton BTNReset;
    private javax.swing.JButton BTNSeleccionTransferencia;
    private javax.swing.JButton BTNTransferencia;
    private javax.swing.JComboBox ComboBox1;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JPanel Panel3;
    private javax.swing.JButton SeleccionCombo;
    private javax.swing.JTextField TXTFondoEmisor;
    private javax.swing.JTextField TXTFondoReceptor;
    private javax.swing.JTextField TXTMontoTransferir;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
