/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static Controlador.VentanaGenerarReciboMensualControlador.RellenaTablaEdificiosSQL;
import Controlador.VentanaGestionAsambleasControlador;
import static Controlador.VentanaGestionAsambleasControlador.ApruebaTrabajoSQL;
import static Controlador.VentanaGestionAsambleasControlador.CalcularClaveAsamblea;
import static Controlador.VentanaGestionAsambleasControlador.RellenaTablaContratosSQL;
import static Controlador.VentanaGestionAsambleasControlador.RellenaTablaTrabajosSQL;
import Controlador.pruebatime;
import static Interfaz.VentanaGestionCuenta.ModeloEdificios;
import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class VentanaGestiondeAsambleas extends javax.swing.JFrame {

    String Fechax;
    public static int  cont;
    public static int Opcion;
    public static DefaultTableModel ModeloTrabajos = new DefaultTableModel();
    
    public static DefaultTableModel ModeloContratos = new DefaultTableModel();
    
    String ClaveContrato;
    String ClaveEdificio;
    String ClaveJunta;
    int NumeroLlamado = 1;
    DateFormat df = DateFormat.getDateInstance();
    DateFormat df1 = DateFormat.getTimeInstance();
    public static String ClaveFondo;
    public static int QuorumMinimo;
    public static float PorcentajeAprob;
    public static int MaximoAPT;
    public static String Clavelibro;
    public static String JuntaActiva;
    public static String ClaveCitaAsamblea;
    public static String ClaveOficina;
    public static String DireccionOficina;
    public static String DireccionEdificio;
    public static String ClaveAsamblea;
    public static int QuorumAsistido;
    public static Float ValorUT;
    
    
    public void cargarInterfazContratos(){
          String x[][]={};
          String columnas[]={"ID Contrato","RifEdificio","NombreEdificio", "NombreOficina"};
          ModeloContratos = new DefaultTableModel(x, columnas);
          Tabla1.setModel(ModeloContratos);
    }        
    
    public void cargarInterfazTrabajos(){
          String x[][]={};
          String columnas[]={"ID Trabajo","Descripcion","Fecha Propuesta", "Costo"};
          ModeloTrabajos = new DefaultTableModel(x, columnas);
          Tabla3.setModel(ModeloTrabajos);
    }        
    
    public VentanaGestiondeAsambleas() {
        initComponents();
         setLocationRelativeTo(null);
       // setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconbuil.png")).getImage() );
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/fondo2.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        PanelLlamados.setVisible(false);
        PanelTabla.setVisible(false);
        PanelFormulario.setVisible(false);
        PanelTrabajos.setVisible(false);
    }
    
   public java.sql.Date convertJavaDateToSqlDate(java.util.Date date) { //CONVIERTE UTIL.DATE A SQL.DATE
        return new java.sql.Date(date.getTime()); }

    public String ConvierteFechas(String FechaInicio){
          try{
                                        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy"); 
                                        java.util.Date fecha=sdf.parse(FechaInicio); 
                                        java.sql.Date FechaNegociacion = convertJavaDateToSqlDate(fecha); //CONVERSIONES A TIPO SQL.DATE
                                        String intento;
                                        intento = (String) FechaNegociacion.toString();
                                        String[] intento2 =intento.split("-");
                                        String intento3 = intento2[0]+intento2[1]+intento2[2];
                                        return (intento3);
          }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error al convertir la fecha."+e.getMessage());
          }                        
        return null;
    
    };
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ComboOpcion = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        PanelLlamados = new javax.swing.JPanel();
        PanelLLamados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtQuorum = new javax.swing.JTextField();
        Fecha = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCostoAnuncio = new javax.swing.JTextField();
        PanelFormulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        votosfavor = new javax.swing.JTextField();
        votoscontra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttopico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        combolugar = new javax.swing.JComboBox();
        HoraInicio = new com.lavantech.gui.comp.DateTimePicker();
        HoraFin = new com.lavantech.gui.comp.DateTimePicker();
        PanelTrabajos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1202, 599));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1202, 599));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel2.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione la operacion que desea realizar"));
        jPanel3.setForeground(new java.awt.Color(254, 254, 254));
        jPanel3.setOpaque(false);
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setVerifyInputWhenFocusTarget(false);

        ComboOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solicitar Asamblea desde Junta", " " }));
        ComboOpcion.setOpaque(false);

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComboOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, Short.MAX_VALUE)
        );

        PanelTabla.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Contratos Existentes"));
        PanelTabla.setOpaque(false);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla1.setOpaque(false);
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        jLabel10.setText("Seleccione El Contrato Correspondiente");

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(PanelTablaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelLlamados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Formulario Para Los LLamados"));
        PanelLlamados.setOpaque(false);

        PanelLLamados.setBorder(javax.swing.BorderFactory.createTitledBorder("Primer LLamado"));
        PanelLLamados.setMaximumSize(new java.awt.Dimension(397, 260));
        PanelLLamados.setMinimumSize(new java.awt.Dimension(397, 260));
        PanelLLamados.setOpaque(false);

        jLabel2.setText("Cuanta Gente Asistio?");

        txtQuorum.setText("10");

        jButton3.setText("Continuar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione la Fecha en la que se realizo el Llamado");

        jLabel3.setText("Indique El Costo del Anuncio de publicacion");

        txtCostoAnuncio.setText("5400");

        javax.swing.GroupLayout PanelLLamadosLayout = new javax.swing.GroupLayout(PanelLLamados);
        PanelLLamados.setLayout(PanelLLamadosLayout);
        PanelLLamadosLayout.setHorizontalGroup(
            PanelLLamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLLamadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLLamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLLamadosLayout.createSequentialGroup()
                        .addComponent(txtCostoAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(PanelLLamadosLayout.createSequentialGroup()
                        .addGroup(PanelLLamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtQuorum, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        PanelLLamadosLayout.setVerticalGroup(
            PanelLLamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLLamadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(txtQuorum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(PanelLLamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCostoAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLlamadosLayout = new javax.swing.GroupLayout(PanelLlamados);
        PanelLlamados.setLayout(PanelLlamadosLayout);
        PanelLlamadosLayout.setHorizontalGroup(
            PanelLlamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLlamadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLLamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        PanelLlamadosLayout.setVerticalGroup(
            PanelLlamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLLamados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulario de la asamblea"));
        PanelFormulario.setOpaque(false);

        jLabel1.setText("Indique el topico de la Asamblea");

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Indique los votos a Favor");

        jLabel6.setText("Indique los votos en Contra");

        votosfavor.setText("8");

        votoscontra.setText("2");
        votoscontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votoscontraActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccione la hora de inicio");

        jLabel8.setText("Seleccione la hora de inicio");

        txttopico.setText("jTextField3");
        txttopico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttopicoActionPerformed(evt);
            }
        });

        jLabel9.setText("Seleccione el lugar donde ocurrira la Asamblea");

        combolugar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oficina de la Administradora", "Edificio" }));

        javax.swing.GroupLayout PanelFormularioLayout = new javax.swing.GroupLayout(PanelFormulario);
        PanelFormulario.setLayout(PanelFormularioLayout);
        PanelFormularioLayout.setHorizontalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                            .addComponent(txttopico)
                            .addGap(33, 33, 33)))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(votosfavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(votoscontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combolugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        PanelFormularioLayout.setVerticalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txttopico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combolugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(votosfavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(votoscontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addContainerGap())))
                    .addGroup(PanelFormularioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        PanelTrabajos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Trabajos Por Aprobar"));
        PanelTrabajos.setOpaque(false);

        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla3.setOpaque(false);
        Tabla3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla3);

        javax.swing.GroupLayout PanelTrabajosLayout = new javax.swing.GroupLayout(PanelTrabajos);
        PanelTrabajos.setLayout(PanelTrabajosLayout);
        PanelTrabajosLayout.setHorizontalGroup(
            PanelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTrabajosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTrabajosLayout.setVerticalGroup(
            PanelTrabajosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTrabajosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelLlamados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(PanelTrabajos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PanelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelLlamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelTrabajos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(PanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Gestion Asambleas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Opcion = ComboOpcion.getSelectedIndex();
          if (Opcion ==0){
                    cargarInterfazContratos();
                    Tabla1.setEnabled(true);
                    PanelLlamados.setVisible(false);
                    try {
                              RellenaTablaContratosSQL();
                              PanelTabla.setVisible(true);
                    } catch (SQLException ex) {
                              JOptionPane.showMessageDialog(rootPane, ex);
                              Logger.getLogger(VentanaGestiondeAsambleas.class.getName()).log(Level.SEVERE, null, ex);
                    }
          }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
          if (Opcion ==0){
                    int Fila = Tabla1.getSelectedRow();
                    ClaveContrato = (String) Tabla1.getValueAt(Fila, 0);
                    PanelLlamados.setVisible(true);
                    Tabla1.setEnabled(false);
                    //JOptionPane.showMessageDialog(rootPane,"La Clave del contrato es:"+ClaveContrato);
          }
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

          try{
                    if (NumeroLlamado == 1){
                              boolean Valido = true;
                              QuorumAsistido =Integer.parseInt(txtQuorum.getText());
                              String Fpropuesto = df.format(Fecha.getDate());
                              String FechaPropuestoString = ConvierteFechas(Fpropuesto);
                              Fechax = FechaPropuestoString;
                              JOptionPane.showMessageDialog(rootPane,"Clave cont ->"+ClaveContrato);
                              VentanaGestionAsambleasControlador.CalcularLLamadoSQL(ClaveContrato,"1");
                              if (QuorumAsistido > MaximoAPT){
                                        JOptionPane.showMessageDialog(rootPane,"Error, No puede existir un quorum mayor a:"+MaximoAPT);
                                        Valido = false;
                              }
                              if (QuorumMinimo > QuorumAsistido){
                                        JOptionPane.showMessageDialog(rootPane,"Se debera Generar otro llamado ya que no se cumplio con el quorum Minimo");
                                        Valido=false;
                                        VentanaGestionAsambleasControlador.InsertarCitaAsambleaSQL(FechaPropuestoString,Integer.toString(QuorumAsistido),"Asamblea Extraordinaria", JuntaActiva);
                                        VentanaGestionAsambleasControlador.CalcularClaveLibro(ClaveContrato);
                                        VentanaGestionAsambleasControlador.InsertarLIBCIT(Clavelibro,ClaveCitaAsamblea);
                                        
                              }
                              VentanaGestionAsambleasControlador.CalcularClaveFondo(ClaveContrato);
                              String Monto;
                              boolean Correcto = true;
                              Monto =txtCostoAnuncio.getText();
                              //JOptionPane.showMessageDialog(rootPane,"Clave fond->"+ClaveFondo);
                              VentanaGestionAsambleasControlador.InsertaTrabajoAnuncioSQL(Monto, ClaveFondo,Fechax);
                              
                              
                              if ((!Valido) && (Correcto)){
                                        NumeroLlamado++;
                                        txtQuorum.setText("");
                                        Fecha.setDate(null);
                                        PanelLLamados.setBorder(javax.swing.BorderFactory.createTitledBorder("Segundo Llamado"));
                    
                              }
                              else{
                                        PanelTrabajos.setVisible(true);
                                        PanelFormulario.setVisible(true);
                                        jButton3.setEnabled(false);
                                        txtQuorum.setEnabled(false);
                                        Fecha.setEnabled(false);
                                        cargarInterfazTrabajos();
                                        RellenaTablaTrabajosSQL(ClaveContrato);
                              
                              }
                    }
                    if (NumeroLlamado == 2){
                              boolean Valido = true;
                              QuorumAsistido =Integer.parseInt(txtQuorum.getText());
                              String Fpropuesto = df.format(Fecha.getDate());
                              String FechaPropuestoString = ConvierteFechas(Fpropuesto);
                              Fechax = FechaPropuestoString;
                              VentanaGestionAsambleasControlador.CalcularLLamadoSQL(ClaveContrato,"1");
                              if (QuorumAsistido > MaximoAPT){
                                        JOptionPane.showMessageDialog(rootPane,"Error, No puede existir un quorum mayor a:"+MaximoAPT);
                                        Valido = false;
                              }
                              if (QuorumMinimo > QuorumAsistido){
                                        JOptionPane.showMessageDialog(rootPane,"Se debera Generar otro llamado ya que no se cumplio con el quorum Minimo");
                                        Valido=false;
                                        VentanaGestionAsambleasControlador.InsertarCitaAsambleaSQL(FechaPropuestoString,Integer.toString(QuorumAsistido),"Asamblea Extraordinaria", JuntaActiva);
                                        VentanaGestionAsambleasControlador.CalcularClaveLibro(ClaveContrato);
                                        VentanaGestionAsambleasControlador.InsertarLIBCIT(Clavelibro,ClaveCitaAsamblea);
                              }
                              VentanaGestionAsambleasControlador.CalcularClaveFondo(ClaveContrato);
                              String Monto;
                              boolean Correcto = true;
                              Monto =txtCostoAnuncio.getText();
                              //JOptionPane.showMessageDialog(rootPane,"Clave fond->"+ClaveFondo);
                              VentanaGestionAsambleasControlador.InsertaTrabajoAnuncioSQL(Monto, ClaveFondo,Fechax);
                              
                              
                              if ((!Valido) && (Correcto)){
                                        NumeroLlamado++;
                                        txtQuorum.setText("");
                                        Fecha.setDate(null);
                                        PanelLLamados.setBorder(javax.swing.BorderFactory.createTitledBorder("Tercer Llamado"));
                    
                              }
                              else{
                                        PanelTrabajos.setVisible(true);
                                        PanelFormulario.setVisible(true);
                                        jButton3.setEnabled(false);
                                        txtQuorum.setEnabled(false);
                                        Fecha.setEnabled(false);
                                        cargarInterfazTrabajos();
                                        RellenaTablaTrabajosSQL(ClaveContrato);
                              
                              }
                    }
                    if (NumeroLlamado == 3){
                              boolean Valido = true;
                              QuorumAsistido =Integer.parseInt(txtQuorum.getText());
                              String Fpropuesto = df.format(Fecha.getDate());
                              String FechaPropuestoString = ConvierteFechas(Fpropuesto);
                              Fechax = FechaPropuestoString;
                              VentanaGestionAsambleasControlador.CalcularLLamadoSQL(ClaveContrato,"1");
                              if (QuorumAsistido > MaximoAPT){
                                        JOptionPane.showMessageDialog(rootPane,"Error, No puede existir un quorum mayor a:"+MaximoAPT);
                                        Valido = false;
                              }
                              if (QuorumMinimo > QuorumAsistido){
                                        JOptionPane.showMessageDialog(rootPane,"Se debera Generar otro llamado ya que no se cumplio con el quorum Minimo");
                                        Valido=false;
                                        VentanaGestionAsambleasControlador.InsertarCitaAsambleaSQL(FechaPropuestoString,Integer.toString(QuorumAsistido),"Asamblea Extraordinaria", JuntaActiva);
                                        VentanaGestionAsambleasControlador.CalcularClaveLibro(ClaveContrato);
                                        VentanaGestionAsambleasControlador.InsertarLIBCIT(Clavelibro,ClaveCitaAsamblea);
                              }
                              VentanaGestionAsambleasControlador.CalcularClaveFondo(ClaveContrato);
                              String Monto;
                              boolean Correcto = true;
                              Monto =txtCostoAnuncio.getText();
                              //JOptionPane.showMessageDialog(rootPane,"Clave fond->"+ClaveFondo);
                              VentanaGestionAsambleasControlador.InsertaTrabajoAnuncioSQL(Monto, ClaveFondo,Fechax);
                              
                              
                              if ((!Valido) && (Correcto)){
                                        NumeroLlamado++;
                                        txtQuorum.setText("");
                                        Fecha.setDate(null);
                                        PanelLLamados.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuarto Llamado"));
                    
                              }
                              else{
                                        PanelTrabajos.setVisible(true);
                                        PanelFormulario.setVisible(true);
                                        jButton3.setEnabled(false);
                                        txtQuorum.setEnabled(false);
                                        Fecha.setEnabled(false);
                                        cargarInterfazTrabajos();
                                        RellenaTablaTrabajosSQL(ClaveContrato);
                              
                              }
                    }
          }catch(NumberFormatException | SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(rootPane,"Error, los campos deben ser llenados en Numeros"+e);
                    
          }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void votoscontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votoscontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votoscontraActionPerformed

    private void Tabla3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        try {
                    boolean correcto = true;
                    int HorasExtras = 0;
                    String Prueba2 = df1.format(HoraFin.getDate());
                    String [] x2 = Prueba2.split(" ");
                    String [] tiempo2 = x2[0].split(":");
                    if (x2[1].equalsIgnoreCase("pm")){
                              int cambio2 = Integer.parseInt(tiempo2[0]);
                              cambio2 = cambio2+12;
                              tiempo2[0] = Integer.toString(cambio2);
                    }
                    
                    String completo2 = Fechax+tiempo2[0]+tiempo2[1]+tiempo2[2];
                    
                    
                    String Prueba = df1.format(HoraInicio.getDate());
                    String [] x = Prueba.split(" ");
                    String [] tiempo = x[0].split(":");
                    if (x[1].equalsIgnoreCase("pm")){
                              int cambio = Integer.parseInt(tiempo[0]);
                              cambio = cambio+12;
                              tiempo[0] = Integer.toString(cambio);
                    }
                    int HFin1 = Integer.parseInt(tiempo[0]);
                    int HFin = Integer.parseInt(tiempo2[0]);
                    
                    String completo = Fechax+tiempo[0]+tiempo[1]+tiempo[2];

                    
                    int tipo = combolugar.getSelectedIndex();
                    if (tipo ==0){//LA ASAMBLEA ES EN LAS OFICINAS DE LA ADMIN
                    
                              if ((HFin1<8)||(HFin1 >17)){
                                        JOptionPane.showMessageDialog(rootPane,"Error, la oficina trabaja de 8am a 5 pm");
                                        correcto = false;
                              }

                              if ((HFin<8)||(HFin >17)){
                                        JOptionPane.showMessageDialog(rootPane,"Error, la oficina trabaja de 8am a 5 pm");
                                        correcto = false;
                              }
                        
                              if (HFin1>HFin){
                                        JOptionPane.showMessageDialog(rootPane,"Error, la Hora de Fin no puede ser mayor a la Hora de Inicio");
                                        correcto = false;
                              }
                    }else{
                              JOptionPane.showMessageDialog(rootPane,"Generar una Asamblea fuera de las oficinas, Generara Costos Extras.");
                              if (HFin1>HFin){
                                        JOptionPane.showMessageDialog(rootPane,"Error, la Hora de Fin no puede ser mayor a la Hora de Inicio");
                                        correcto = false;
                              }
                              int MinutosFinales =Integer.parseInt(tiempo2[1]);
                              if (MinutosFinales != 0)
                                        HorasExtras++;
                              if (HFin > 21 ){
                                        int otro = HFin - 21;
                    //                    JOptionPane.showMessageDialog(rootPane, otro);
                                        if (otro > 0)
                                                  HorasExtras= HorasExtras+otro;
                              }
                              
                    //JOptionPane.showMessageDialog(rootPane,"Las Horas Extras son:"+HorasExtras);
                    }
                    
                    if (correcto){
                    
                    
                    
                    VentanaGestionAsambleasControlador.CalcularClaveOficinaDireccion(ClaveContrato);
                    
                    String topico = txttopico.getText();
                    String tipop = "EXTRAORDINARIA";
                    String Lugar;
                    if (combolugar.getSelectedIndex() == 0)
                              Lugar=DireccionOficina;
                    else
                                Lugar = DireccionEdificio;
                    VentanaGestionAsambleasControlador.InsertarAsambleaSQL(topico, tipop,ClaveOficina, Lugar);
                    
                    int filaSeleccionada = Tabla3.getSelectedRow();
                    String ClaveTrabajo = ((String)Tabla3.getValueAt(filaSeleccionada, 0));
                    CalcularClaveAsamblea();
                    int VotosFavor = Integer.parseInt(votosfavor.getText());
                    int VotosContra = Integer.parseInt(votoscontra.getText());
                    if ((VotosContra+VotosFavor) != (QuorumAsistido))
                    {
                              correcto = false;
                              JOptionPane.showMessageDialog(null, "Error, la suma de los votos debe ser igual al quorum asistido "+QuorumAsistido);
                    }
                    if (correcto)
                    {
                              VentanaGestionAsambleasControlador.InsertaTrabajoMayorSQL(Integer.toString(VotosFavor),Integer.toString( VotosContra), ClaveAsamblea, ClaveTrabajo);
                             // JOptionPane.showMessageDialog(rootPane,VotosFavor);
                              //JOptionPane.showMessageDialog(rootPane,QuorumAsistido);
                              float p = (VotosFavor *100)/QuorumAsistido;
                              //JOptionPane.showMessageDialog(rootPane,"Porcentaje"+PorcentajeAprob);
                              //JOptionPane.showMessageDialog(rootPane,"Resul" +p);
                              if (p >PorcentajeAprob){
                                        JOptionPane.showMessageDialog(rootPane,"TRABAJO APROBADO");
                                        ApruebaTrabajoSQL(ClaveTrabajo);
                                        VentanaGestiondeAsambleas nueva = new VentanaGestiondeAsambleas();
                                        nueva.setVisible(true);

                              }
                              else{
                                        JOptionPane.showMessageDialog(rootPane,"TRABAJO NEGADO, SI SE DESEA SE PUEDE VOLVER A LLEVAR A ASAMBLEA.");
                                         VentanaGestiondeAsambleas nueva = new VentanaGestiondeAsambleas();
                                        nueva.setVisible(true);

                              }
                              
                              if (combolugar.getSelectedIndex() == 1){
                                        VentanaGestionAsambleasControlador.InsertaHor_DETSQL(completo,completo2, "1", ClaveAsamblea);
                                        VentanaGestionAsambleasControlador.CalcularValorUT();
                                        Float ValorAsamblea = 6*ValorUT;
                                        VentanaGestionAsambleasControlador.InsertaTrabajoCostoAsambleaSQL(Float.toString(ValorAsamblea), ClaveFondo, Fechax);
                                        if (HorasExtras > 0){
                                                  Float MontoExtra = 4 * HorasExtras * ValorUT;
                                                  VentanaGestionAsambleasControlador.InsertaTrabajoCostoAsamblea2SQL(Float.toString(MontoExtra), ClaveFondo, Fechax);

                                        }
                              
                              }
                    }
                    this.dispose();
                    }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGestiondeAsambleas.class.getName()).log(Level.SEVERE, null, ex);
        }
        








// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txttopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttopicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttopicoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VentanaMenuPrincipal nueva;
        try {
            nueva = new VentanaMenuPrincipal();
            nueva.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Error, Debe ingresar desde el LogIn");
              VentanaLogIn x = new VentanaLogIn();
              x.setVisible(true);
              this.dispose();
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiondeAsambleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiondeAsambleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiondeAsambleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiondeAsambleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestiondeAsambleas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboOpcion;
    private com.toedter.calendar.JDateChooser Fecha;
    private com.lavantech.gui.comp.DateTimePicker HoraFin;
    private com.lavantech.gui.comp.DateTimePicker HoraInicio;
    private javax.swing.JPanel PanelFormulario;
    private javax.swing.JPanel PanelLLamados;
    private javax.swing.JPanel PanelLlamados;
    private javax.swing.JPanel PanelTabla;
    private javax.swing.JPanel PanelTrabajos;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla3;
    private javax.swing.JComboBox combolugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCostoAnuncio;
    private javax.swing.JTextField txtQuorum;
    private javax.swing.JTextField txttopico;
    private javax.swing.JTextField votoscontra;
    private javax.swing.JTextField votosfavor;
    // End of variables declaration//GEN-END:variables
}
